[tools]
bun = "latest"
atuin = "latest"
starship = "latest"
jj = "latest"
lazygit = "latest"
"ubi:idursun/jjui" = "latest"
"ubi:dector/bang" = "latest"
"ubi:dector/serv" = "latest"
bat = "latest"
"ubi:dector/lampa" = "latest"
chezmoi = "latest"
task = "latest"
"ubi:umlx5h/gtrash" = "latest"
go = "latest"
"ubi:j178/prek" = "latest"
usage = "latest"
fzf = "latest"
zig = "latest"
cmake = "latest"
rust = "latest"
just = "latest"
duf = "latest"
"go:github.com/oligot/go-mod-upgrade" = "latest"
glow = "latest"
choose = "latest"
golangci-lint = "latest"
jq = "latest"
"ubi:block/goose" = "latest"
uv = "latest"
yazi = "latest"
"ubi:tinygo-org/tinygo" = "latest"
"ubi:neovim/neovim" = { version = "latest", exe = "nvim" }
java = "latest"
node = "latest"
gemini = "latest"
tokei = "latest"
pandoc = "latest"
opencode = "latest"
codex = "latest"
ttyd = "latest"
"npm:@marp-team/marp-cli" = "latest"
rg = "latest"
"ubi:philschmid/mcp-cli" = "latest"
pnpm = "latest"
pi = "latest"
lua = "latest"

[settings]
idiomatic_version_file_enable_tools = ["java"]
experimental = true

#"ubi:abenz1267/walker" = "latest"
#"ubi:kainctl/isd" = "latest"
#"ubi:fujiapple852/trippy" = { version = "latest", exe = "trip" }
#"npm:vite" = "latest"
#pnpm = "latest"
#"ubi:golangci/golangci-lint" = "latest"
#"ubi:emprcl/runal" = "latest"
#hk = "latest"
#gemini = "latest"
#"pipx:httpie" = "latest"
#"ubi:nushell/nushell" = { version = "latest", exe = "nu" }
#sentry = "latest"
#rust = "latest"
#"ubi:tailwindlabs/tailwindcss" = "latest"
#zellij = "latest"
#"ubi:afnanenayet/diffsitter" = "latest"
#"npm:@github/copilot" = "latest"

